---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinnaker-demo-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - spinnaker-demo-gateway
  http:
  - route:
    - destination:
        host: spinnaker-demo.stg.svc.cluster.local
        subset: v1
      weight: 95
    - destination:
        host: spinnaker-demo-canary.stg.svc.cluster.local
        subset: v1
      weight: 5
